### ISSUE TITLE
React Tag All suggestions are not showing hiding behind the div

### ISSUE THREAD

**Issue by pramodkumar-dcpl** [i-like-robots/react-tags#118]
Hi,

Facing an issue regarding the suggestion in the react tag, All options are not showing properly hide behind the div, Screen shot attached.

![issue-reacttag](https://user-images.githubusercontent.com/20681484/37162716-fdef860e-231b-11e8-814a-64a5918d731f.png)

I have tried the z-index, but my tab below this is not allowing me to do anything, means click is not working on the tab below the react tag.

Also when i apply z-index and choose the suggestion then i am also not able to click on my tab, So, is there is any way that after selecting the suggestion we can kill the div so that i can work with my tab panel too.

**Comment by zenVentzi** [comment]
Facing the same issue here. Any updates? It looks like some work needs to be done with React Portals for it to work properly. I.e. the dropdown should be portalled to some top-level div.

**Comment by i-like-robots** [comment]
I don't have the capacity to debug individual implementations but it appears to me both of you may be having issues with [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). I've marked the issue as a question for the community to answer as I believe this is an issue with integration rather than with the component.

**Comment by zenVentzi** [comment]
Stacking context is indeed the issue and React Portals is the first solution that comes to mind.

**Comment by i-like-robots** [comment]
Closing this as I don't believe there are any changes to the component required.
