### ISSUE TITLE
Pass event on handleDelete and on handleAdd

### ISSUE THREAD

**Issue by melenaos** [i-like-robots/react-tags#144]
I want to use a common function for handleDelete and handleAdd and the way I am doing now for other inputs is by using a data-name to get the state member i need to update.

`<input data-name="example1" value={this.state.example1} onChange="onChange" />`

That way I can get the data-name using the event from the onChange function

`onchange(event){const name= event.target.getAttribute('data-name')....}`

React-Tags is passing `i` on `handleAdd` and `tag` on `handleDelete`.

It would be beneficial to pass `event` next to these two parameters so we can get a handle to the element triggering this event.

**Comment by solvr-claus** [comment]
Lovely component, but I too would like to be able to get to the actual tag instance through an event object passed to onDelete and onAddition. That way we could perhaps set different classes on the tags. Any chance of this happening?

**Comment by i-like-robots** [comment]
It's possible to add an additional argument to all of the callbacks. This could be a ref to a relevant DOM element (created using `createRef()`) or an instance of the component (`this`) but I'm unclear what the use cases are for either.

Could you provide more information about your implementations so that I can understand which may be more appropriate?

**Comment by solvr-claus** [comment]
We managed to solve our use case with a custom tag component. So now everything works like a charm. Thanks :)
