### ISSUE TITLE
Tab not working

### ISSUE THREAD

**Issue by SistemasSouza** [i-like-robots/react-tags#157]
1- Add Tag in pressed button tab not working nothing happens
2- filter not working if input are empty 
3- mouse click too not working 

chrome version 74

my code 

![image](https://user-images.githubusercontent.com/13488005/57330590-e2224400-70ec-11e9-9a75-0f9379fca78f.png)

stateless component

**Comment by i-like-robots** [comment]
Hi @SistemasSouza are you able to share an example demonstrating this behaviour?

**Comment by jefbernardino** [comment]
Hi @i-like-robots -  I have the same problem here.
My project used version 5.8 and it did not work, and today I upgraded to 5.11, and the problem persists.

Please, check this link:
[https://codepen.io/jefbernardino/pen/RmGxoZ]

**Comment by jefbernardino** [comment]
To insert new tags, it is necessary to use allowNew now, correct?
I remember that just pressing tab to insert a new tag using the handleAddition option...

**Comment by i-like-robots** [comment]
@jefbernardino That's right, to add a tag which is not suggested you must enable the `allowNew` option.

And to clarify the intended behaviour of the component; in order to add a suggested tag by pressing  a delimiter key - such as return, enter, or tab - you must first select a suggestion from the list displayed.
