### ISSUE TITLE
Suggestion issues

### ISSUE THREAD

**Issue by ron766** [i-like-robots/react-tags#160]
1. Words typed in input box are being cut in the suggestions
2. For some suggestions the text is not appearing

**Comment by i-like-robots** [comment]
Hi @ron766 are you able to share a demo showing this behaviour?

**Comment by ron766** [comment]
> Hi @ron766 are you able to share a demo showing this behaviour?

[https://drive.google.com/open?id=18MLgWNQqkGi80pq9pF8i6FqMwQCAsDIr](url)
You can check the demo here.
Node version 6.12.0. Tried on 10.15.3 also but faced the same issue.
React version 16.8.x
'react-tag-autocomplete' version 5.10.0

`import ReactTags from 'react-tag-autocomplete';`
`<ReactTags
                        tags={this.state.tags}
                        minQueryLength={0}
                        maxSuggestionsLength={maxSuggestionsLength}
                        autoFocus={true}
                        suggestions={this.state.suggestions}
                        handleDelete={this.handleDelete}
                        handleAddition={this.handleAddition}
                        placeholder={placeholder}
                       />`
Hope I expressed myself correctly.

**Comment by i-like-robots** [comment]
Thanks for the video @ron766, I can see the issue clearly.

Unfortunately I suspect this is an issue caused by your existing styles conflicting with some provided by this component. I can't help to debug individual integrations.

However, if you are able to recreate the issue in a Codepen or similar then I'd be happy to have a look.
