### ISSUE TITLE
IE11 issue not supported

### ISSUE THREAD

**Issue by muhabalwan** [i-like-robots/react-tags#198]
issue in **react-tag-autocomplete v5.11.2** with **IE11** 
I can add existing ones which is perfect but if I add `allowNew` property it will not work on IE11  
<img width="635" alt="Screenshot 2020-03-11 at 1 47 53 PM" src="https://user-images.githubusercontent.com/5458873/76418785-8923dc00-639f-11ea-9668-db71664bb15e.png">
<img width="304" alt="Screenshot 2020-03-11 at 1 47 46 PM" src="https://user-images.githubusercontent.com/5458873/76418791-8cb76300-639f-11ea-8a96-0e82b3626f98.png">
Maybe this will help?
<img width="1256" alt="Screenshot 2020-03-11 at 1 53 39 PM" src="https://user-images.githubusercontent.com/5458873/76418904-bff9f200-639f-11ea-8c2f-c8de962efd57.png">

**Comment by i-like-robots** [comment]
I assume you're already implementing several polyfills in order to use React ([full details are here](https://reactjs.org/docs/javascript-environment-requirements.html) but in summary React uses `Set`, `Map` and `requestAnimationFrame`, none of which are supported by IE11) so I'd recommend including a polyfill in the same manner for `findIndex` as well.
