### ISSUE TITLE
Increase Minimum supported node version

### ISSUE THREAD

**Issue by sibiraj-sr** [i-like-robots/react-tags#216]
The library should support whatever react supports or at-least max range. Since this is a UI component, there is no need to specify node versions.

## Expected behaviour

Should support node versions whatever react supports.

https://github.com/facebook/react/blob/master/packages/react/package.json#L28-L30

## Current behaviour

In v6. the node version has been increased to v10. this prevents us from installing the lib on v8 node

## Steps to Reproduce

Steps to reproduce the problem:

1. Install react-tags with yarn in v8 node

## Screenshots

<img width="1440" alt="Screenshot 2020-08-06 at 1 04 30 PM" src="https://user-images.githubusercontent.com/45618743/89505576-7ba43e00-d7e7-11ea-83ef-4708c66aa270.png">

## Your environment

- OS: Mac
- Browser: No
- Nodejs: v8
- Version of the component: [e.g. 6.x]
- React version: [e.g. 16.13]

**Comment by i-like-robots** [comment]
Thanks for your question @sibiraj-s. I'm afraid I don't intend to offer any support for older Node versions and Node 8 reached its end of life in 2019. Because the component can be rendered on the server-side using the `react-dom/server` package the Node version specified in the manifest is relevant.

For now if the component does still work with Node v8, and you do really need to install the package using Yarn, I believe you can do so using the `--ignore-engines` flag. However, this is completely at your own risk and may break in any future release!

**Comment by sibiraj-sr** [comment]
Thanks for the clarification. I did totally forgot the server side thing. 

Yeah. `--ignore-engines` is too much riskier. we have a monorepo with both BE and FE code. things might not end up good. I might have to check if anything else could be done for this package alone. if nothing works I might have to fork it and use the fork directly.
