### ISSUE TITLE
Unknown prop `autoresize` on <input> tag

### ISSUE THREAD

**Issue by shoetten** [i-like-robots/react-tags#27]
Any reason you reversed 6fb7fd6f8e7a4f07855f5df3f09a42213554c060 in 5b7bf5d?
React throws this ugly error again..

``
"Warning: Unknown prop `autoresize` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
``

**Comment by i-like-robots** [comment]
Afraid so, I've been switching to [buble](https://gitlab.com/Rich-Harris/buble) which only supports object spread in some circumstances (because it's still only a stage 2 proposal).

I've also been planning a refactor of the input component for a while and this is a good nudge to do it - it should be out within the next few days.

**Comment by shoetten** [comment]
Thanks for the info. That's too bad, but i'm looking forward to the refactor..

**Comment by dmmulroy** [comment]
Any update on this refactor?

**Comment by i-like-robots** [comment]
5.0 was released August 16th =]

**Comment by i-like-robots** [comment]
There is an update section in the readme: https://github.com/i-like-robots/react-tags#upgrading-from-4x-to-50

The changlog also has more info about upgrading: https://github.com/i-like-robots/react-tags/blob/master/CHANGELOG.md

**Comment by dmmulroy** [comment]
Cool, thanks!
