### ISSUE TITLE
Calculated width of input isn't correct

### ISSUE THREAD

**Issue by thienanle** [i-like-robots/react-tags#52]
Love the updates you made to `react-tags`. I'm just seeing an issue where the width of `input` isn't calculated correctly (it's narrower than the text). Perhaps it's the font I'm using? How is width calculated?

![oct-23-2016 11-59-51](https://cloud.githubusercontent.com/assets/874402/19623523/7695e952-9918-11e6-894a-c6243e2008a0.gif)

Note: I'm using styles.css from [the examples](https://github.com/i-like-robots/react-tags/blob/b1a8d5bd5681931f4ba1cfb3c3507ebd70482832/example/styles.css).

**Comment by i-like-robots** [comment]
The technique for resizing is quite simple... there's a hidden `<div>` element onto which the styles of the input are copied. When the value of the input changes that value is also copied into the hidden element, the width measured and that applied back to the input...

Perhaps some important styles are not being copied across (the list [is here](https://github.com/i-like-robots/react-tags/blob/master/lib/Input.js#L14-L20)). Could you let me know the browser and if possible setup a demo I could investigate?

**Comment by thienanle** [comment]
Found the issue. The styles get copied over via JS on `componentDidMount`, which for some reason is happening *before* css-modules styles go into affect. At this point, my `input` still has the default Chrome user agent styles (`font: 11px BlinkMacSystemFont`).

Probably a better question for the folks over at [css-modules](https://github.com/css-modules/css-modules), but posting it here in case any else has the same issue.

**Comment by i-like-robots** [comment]
Glad you've found the issue, I hope there's an easy solution =]

**Comment by thienanle** [comment]
After more investigation my only conclusion is that for `react-tags` to work properly, CSS must load before JS executes. The easiest way is to put the css `link` before the `script` tag in HTML. If using `require` to include the CSS, the styles are inline with the html that gets outputted, which caused the issue I was seeing. I was able to solve this by using `extract-text-webpack-plugin` to extract the CSS and place it before the `script` tag in my html.

```
{
        test: /\.css/,
        loader: ExtractTextPlugin.extract(
          'style-loader',
          `css-loader?${JSON.stringify({
            modules: true,
            localIdentName: isDebug ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',
            // CSS Nano http://cssnano.co/options/
            minimize: !isDebug,
            importLoaders: 1,
          })}!postcss-loader`
        ),
        // Let's use CSS Modules except in external libraries (ie stuff in node_modules)
        exclude: /node_modules/,
      },
```

**Comment by joekrill** [comment]
We have a situation where we initially render the component inside a collapsed div -- so the width is getting set to 2px regardless of the content (`updateInputWidth` adds 2 to it's calculation, that's why we're seeing 2 here instead of 0). So I'm not sure if there's a better way to determine the width, or trigger a recalculation.

**Comment by i-like-robots** [comment]
@joekrill adding is very arbitrary I admit... it's simply because getting an accurate value, cross-browser was never quite right. I'm open to suggestions on how to improve this!

A re-calculation will be triggered any time the input value is changed, it may be triggered manually by digging through the internals but I can't provide any guarantee as it's not a public API.

**Comment by joekrill** [comment]
@i-like-robots Yeah I was trying to think of a possible solution but haven't really come up with anything. One thing I would suggest is at least allowing the parent component to "force" a recalc. This could really be done by just allowing the parent component to toggle the `autoresize` prop. Currently that doesn't actually do anything, because the `componentDidUpdate` call will only recalculate if the input text changes (and `autoresize` is true). Which I think is a bug -- it should probably also update the input width when any property affecting the width changes, and that would include the `autoresize` property itself. And it should probably also _remove_ the width style if `autoresize` is updated to `false. 

Anyway, I submitted PR #56 to handle those other props.
