### ISSUE TITLE
AutoFocus={false} is not always respected

### ISSUE THREAD

**Issue by ZephD** [i-like-robots/react-tags#66]
I set autofocus to false as a default prop and/or as a prop input, yet sometimes if I navigate away and back, the field is focused automatically.

This is especially noticeable when using minQueryLength={0}, as the dropbox appears despite never selecting the field.

**Comment by i-like-robots** [comment]
I'm not able to recreate this issue (testing in FF 52 and Chrome 56). Are you able to share an example demonstrating the problem? Which browsers have you found are affected?

For reference, autofocus is implemented [in the component](https://github.com/i-like-robots/react-tags/blob/master/lib/Input.js#L34) rather than using the [autofocus attribute](https://developer.mozilla.org/en/docs/Web/HTML/Element/input#attr-autofocus) to ensure the behavior consistent.

**Comment by ZephD** [comment]
It would be difficult to create a react app to mimic this behaviour.
Thats a good way to implement the focus ability.

Does the input.focus() get cached internally? because if you focus it once, unmount, then remount, the focus attribute may be set despite by this cache despite the autofocus being false (ie it wont call .focus() but doesnt need to as something else sets it)

**Comment by i-like-robots** [comment]
As I'm not able to recreate this behavior nor have received any more feedback about it I'll close this issue for now.

**Comment by ZephD** [comment]
> Do you have a fiddle I can edit up?
