### ISSUE TITLE
MouseDown causes bugs - use onClick instead?

### ISSUE THREAD

**Issue by Billy-** [i-like-robots/react-tags#71]
We have a react-tags component at the bottom of a modal. If you click on a suggested tag which extends below the bottom of the modal, the tag is selected on mouseDown, the suggestions disappear, then mouseUp happens on the backdrop, causing the modal to close.

Is there any reason you are using onMouseDown instead of onClick or onMouseUp?

**Comment by i-like-robots** [comment]
The suggestions list is hidden on blur and because focus is shifted before the click event is triggered this means the event happens outside of the list, so selections cannot be made with a mouse:

![tags](https://cloud.githubusercontent.com/assets/271645/25408932/d1c7180c-2a07-11e7-889f-29d33ba99893.gif)

This was a compromise at the time to have more simple code.

**Comment by Billy-** [comment]
Ah. I had a feeling there would have been a reason for it. Would it be possible to check if the suggestion list is focused on the suggestion list on blur of the input, in which case prevent the list from being hidden.

This would mean adding similar logic to the suggestion list to check when it's blurred and if the focus is on the input?
